index:
    path: /
    defaults: { _controller: 'App:Global:index' }

global_room:
    path: /global_room
    defaults: { _controller: 'App:Global:globalRoom' }

roots:
    path: /roots
    defaults: { _controller: 'App:Global:roots' }

project:
    path: /project
    defaults: { _controller: 'App:Global:project' }
