proposal_show:
    path: /show/{slug}
    defaults: { _controller: 'App:Proposal:show'}

proposal_add:
    path: /add/{themeSlug}
    defaults: { _controller: 'App:Proposal:add' }

proposal_edit:
    path: /edit/{slug}
    defaults: { _controller: 'App:Proposal:edit' }

proposal_edit_motivation:
    path: /edit/motivation/{slug}
    defaults: { _controller: 'App:Proposal:editMotivation' }

proposal_publish:
    path: /publish/{slug}
    defaults: { _controller: 'App:Proposal:publish' }

proposal_delete:
    path: /delete/{slug}
    defaults: { _controller: 'App:Proposal:delete' }

proposal_support:
    path: /support/{slug}
    defaults: { _controller: 'App:Proposal:support' }

proposal_removesupport:
    path: /removesupport/{slug}
    defaults: { _controller: 'App:Proposal:removeSupport' }

proposal_oppose:
    path: /oppose/{slug}
    defaults: { _controller: 'App:Proposal:oppose' }

proposal_removeoppose:
    path: /removeoppose/{slug}
    defaults: { _controller: 'App:Proposal:removeOppose' }
